import os
import json
import time
from google import genai
from google.genai import types
from dotenv import load_dotenv
from utils.key_rotator import KeyRotator

load_dotenv()

keys = [os.getenv(f"GEMINI_KEY_{i}") for i in range(1, 5)]
rotator = KeyRotator(keys)

SYSTEM_PROMPT = """You are Healthify, an expert AI medical triage 
assistant for rural Indian healthcare workers.

You will receive ML model predictions and patient data. Your job is 
to enhance these predictions with clinical reasoning.

STRICT RULES:
- Return ONLY valid JSON, no markdown, no code blocks, no extra text
- Never suggest specific drug names or dosages
- Consider India-specific diseases: dengue, malaria, typhoid, 
  chikungunya, leptospirosis
- Write for ASHA/ANM health worker audience, simple clear language
- Always end doctor_summary with exactly this sentence: 
  "This summary was generated by Healthify AI and is not a 
  replacement for clinical diagnosis."
- Red flags must be specific and actionable

Return this EXACT JSON structure, nothing else:
{
  "top_conditions": [
    {
      "name": "string",
      "confidence": "high|medium|low",
      "match_score": integer between 0-100,
      "reasoning": "2 sentences explaining why this matches the symptoms"
    }
  ],
  "red_flags": ["specific warning string"],
  "recommended_tests": ["test name"],
  "home_care": ["specific actionable tip"],
  "when_to_escalate": ["specific condition to watch for"],
  "doctor_summary": "3 professional sentences. End with AI disclaimer."
}"""


def enhance_with_gemini(patient_data: dict, ml_result: dict) -> dict:
    key = rotator.get_key()
    
    if key is None:
        print("No Gemini keys available, using ML result")
        return ml_result

    user_prompt = f"""
PATIENT DATA:
- Age: {patient_data.get('age')}, Gender: {patient_data.get('gender')}
- Symptoms: {', '.join(patient_data.get('symptoms', []))}
- Duration: {patient_data.get('duration_days')} days
- Severity: {patient_data.get('severity')}/10
- Existing conditions: {', '.join(patient_data.get('existing_conditions', [])) or 'None'}
- Pregnant: {patient_data.get('is_pregnant', False)}
- Recent travel: {patient_data.get('recent_travel', False)}

ML MODEL PREDICTIONS:
- Urgency: {ml_result.get('urgency')}
- Top conditions: {[c['name'] for c in ml_result.get('top_conditions', [])]}
- Red flags from rule engine: {ml_result.get('red_flags', [])}

Enhance these predictions with clinical reasoning.
Keep the same top conditions but add detailed reasoning.
Add India-relevant context if applicable.
Return ONLY the JSON object, no other text.
"""

    full_prompt = SYSTEM_PROMPT + "\n\n" + user_prompt

    try:
        client = genai.Client(api_key=key)
        
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=full_prompt,
            config=types.GenerateContentConfig(
                temperature=0.1,
                max_output_tokens=1200
            )
        )

        raw_text = response.text.strip()

        # Strip markdown fences if present
        if raw_text.startswith("```"):
            lines = raw_text.split("\n")
            lines = [l for l in lines if not l.startswith("```")]
            raw_text = "\n".join(lines).strip()

        gemini_data = json.loads(raw_text)

        # Merge: keep ML urgency/urgency_reason, replace rest with Gemini
        merged = ml_result.copy()
        merged["top_conditions"] = gemini_data.get(
            "top_conditions", ml_result["top_conditions"])
        merged["red_flags"] = gemini_data.get(
            "red_flags", ml_result["red_flags"])
        merged["recommended_tests"] = gemini_data.get(
            "recommended_tests", ml_result["recommended_tests"])
        merged["home_care"] = gemini_data.get(
            "home_care", ml_result["home_care"])
        merged["when_to_escalate"] = gemini_data.get(
            "when_to_escalate", ml_result["when_to_escalate"])
        merged["doctor_summary"] = gemini_data.get(
            "doctor_summary", ml_result["doctor_summary"])
        merged["source"] = "ml+gemini"

        print("Gemini enhancement successful!")
        return merged

    except Exception as e:
        error_str = str(e)
        if "429" in error_str or "quota" in error_str.lower():
            rotator.mark_rate_limited(key)
            print("Rate limit hit, rotating key and retrying...")
            # Get next key and retry once
            next_key = rotator.get_key()
            if next_key and next_key != key:
                return enhance_with_gemini(patient_data, ml_result)
        print(f"Gemini error: {error_str}")
        return ml_result
